# Generated by Django 4.2.5 on 2023-09-27 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal_card',
            name='age',
            field=models.IntegerField(verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='animal_card',
            name='breed',
            field=models.CharField(max_length=20, verbose_name='Порода'),
        ),
        migrations.AlterField(
            model_name='animal_card',
            name='height',
            field=models.IntegerField(verbose_name='Рост'),
        ),
        migrations.AlterField(
            model_name='animal_card',
            name='nickname',
            field=models.CharField(max_length=20, verbose_name='Кличка питомца'),
        ),
        migrations.AlterField(
            model_name='animal_card',
            name='weight',
            field=models.IntegerField(verbose_name='Вес'),
        ),
        migrations.AlterField(
            model_name='breed',
            name='breed',
            field=models.CharField(max_length=20, verbose_name='Порода питомца'),
        ),
        migrations.AlterField(
            model_name='data',
            name='data',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='name',
            field=models.CharField(max_length=15, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='profesh',
            field=models.CharField(max_length=20, verbose_name='Профессия'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='surname',
            field=models.CharField(max_length=20, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='owner_card',
            name='address',
            field=models.CharField(max_length=50, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='owner_card',
            name='breed',
            field=models.CharField(max_length=20, verbose_name='Порода питомца'),
        ),
        migrations.AlterField(
            model_name='owner_card',
            name='email',
            field=models.EmailField(max_length=30, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='owner_card',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='owner_card',
            name='nickname',
            field=models.CharField(max_length=20, verbose_name='Кличка'),
        ),
        migrations.AlterField(
            model_name='owner_card',
            name='surname',
            field=models.CharField(max_length=20, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='owner_card',
            name='telefon',
            field=models.CharField(max_length=12, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='prices',
            name='cupping',
            field=models.IntegerField(verbose_name='Купирование'),
        ),
        migrations.AlterField(
            model_name='prices',
            name='delivery_reception',
            field=models.IntegerField(verbose_name='Прием родов'),
        ),
        migrations.AlterField(
            model_name='prices',
            name='first_inspection',
            field=models.IntegerField(verbose_name='Первичный осмотр'),
        ),
        migrations.AlterField(
            model_name='prices',
            name='haircuts',
            field=models.IntegerField(verbose_name='Стрижка'),
        ),
        migrations.AlterField(
            model_name='prices',
            name='laboratory_tests',
            field=models.IntegerField(verbose_name='Лабораторные исследования'),
        ),
        migrations.AlterField(
            model_name='prices',
            name='nail_trimming',
            field=models.IntegerField(verbose_name='Обрезка ногтей'),
        ),
        migrations.AlterField(
            model_name='prices',
            name='stomat_ment',
            field=models.IntegerField(verbose_name='Стомотологическое лечение'),
        ),
        migrations.AlterField(
            model_name='services',
            name='cupping',
            field=models.TextField(max_length=500, verbose_name='Купирование'),
        ),
        migrations.AlterField(
            model_name='services',
            name='delivery_reception',
            field=models.TextField(max_length=500, verbose_name='Прием родов'),
        ),
        migrations.AlterField(
            model_name='services',
            name='first_inspection',
            field=models.TextField(max_length=500, verbose_name='Первичный осмотр'),
        ),
        migrations.AlterField(
            model_name='services',
            name='haircuts',
            field=models.TextField(max_length=500, verbose_name='Стрижка'),
        ),
        migrations.AlterField(
            model_name='services',
            name='laboratory_tests',
            field=models.TextField(max_length=500, verbose_name='Лабораторные исследования'),
        ),
        migrations.AlterField(
            model_name='services',
            name='nail_trimming',
            field=models.TextField(max_length=500, verbose_name='Обрезка ногтей'),
        ),
        migrations.AlterField(
            model_name='services',
            name='stomat_ment',
            field=models.TextField(max_length=500, verbose_name='Стомотологическое лечение'),
        ),
        migrations.AlterField(
            model_name='status',
            name='prof',
            field=models.CharField(choices=[('хирург', 'хирург'), ('стоматолог', 'стоматолог'), ('терапевт', 'терапевт'), ('дерматолог', 'дерматолог')], max_length=20, verbose_name='Профессия'),
        ),
        migrations.AlterField(
            model_name='vet_clinic',
            name='animal_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.animal_card', verbose_name='Питомец'),
        ),
        migrations.AlterField(
            model_name='vet_clinic',
            name='breeds',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.breed', verbose_name='Породы'),
        ),
        migrations.AlterField(
            model_name='vet_clinic',
            name='data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.data', verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='vet_clinic',
            name='doctor',
            field=models.ManyToManyField(to='catalog.doctors', verbose_name='Профессия'),
        ),
        migrations.AlterField(
            model_name='vet_clinic',
            name='owner_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.owner_card', verbose_name='Владелец питомца'),
        ),
        migrations.AlterField(
            model_name='vet_clinic',
            name='prices',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.prices', verbose_name='Цена услуг'),
        ),
        migrations.AlterField(
            model_name='vet_clinic',
            name='services',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.services', verbose_name='Услуги'),
        ),
        migrations.AlterField(
            model_name='vet_clinic',
            name='servis_price',
            field=models.DecimalField(decimal_places=3, max_digits=9, verbose_name='Стоимость услуг'),
        ),
        migrations.AlterField(
            model_name='vet_clinic',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='catalog.status', verbose_name='Специалист'),
        ),
    ]
