# Generated by Django 4.2.5 on 2023-09-27 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_animal_card_age_alter_animal_card_breed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='cupping',
        ),
        migrations.RemoveField(
            model_name='services',
            name='delivery_reception',
        ),
        migrations.RemoveField(
            model_name='services',
            name='first_inspection',
        ),
        migrations.RemoveField(
            model_name='services',
            name='haircuts',
        ),
        migrations.RemoveField(
            model_name='services',
            name='laboratory_tests',
        ),
        migrations.RemoveField(
            model_name='services',
            name='nail_trimming',
        ),
        migrations.RemoveField(
            model_name='services',
            name='stomat_ment',
        ),
        migrations.AddField(
            model_name='services',
            name='servis',
            field=models.CharField(blank=True, choices=[('Первичный осмотр', 'Первичный осмотр'), ('Лабораторные исследования', 'Лабораторные исследования'), ('Купирование', 'Купирование'), ('Стрижка', 'Стрижка'), ('Обрезка ногтей', 'Обрезка ногтей'), ('Прием родов', 'Прием родов'), ('Стомотологическое лечение', 'Стомотологическое лечение')], max_length=30, null=True, verbose_name='Услуги'),
        ),
        migrations.AlterField(
            model_name='data',
            name='data',
            field=models.DateField(),
        ),
    ]
