# Generated by Django 4.2.5 on 2023-09-27 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_vet_clinic_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vet_clinic',
            name='services',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.services', verbose_name='Услуги'),
        ),
    ]
