# Generated by Django 4.2.5 on 2023-09-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_vet_clinic_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prices',
            name='cupping',
        ),
        migrations.RemoveField(
            model_name='prices',
            name='delivery_reception',
        ),
        migrations.RemoveField(
            model_name='prices',
            name='first_inspection',
        ),
        migrations.RemoveField(
            model_name='prices',
            name='haircuts',
        ),
        migrations.RemoveField(
            model_name='prices',
            name='laboratory_tests',
        ),
        migrations.RemoveField(
            model_name='prices',
            name='nail_trimming',
        ),
        migrations.RemoveField(
            model_name='prices',
            name='stomat_ment',
        ),
        migrations.AddField(
            model_name='prices',
            name='price',
            field=models.CharField(blank=True, choices=[('350$', 'Первичный осмотр'), ('750$', 'Лабораторные исследования'), ('1200$', 'Купирование'), ('450$', 'Стрижка'), ('600$', 'Обрезка ногтей'), ('1500$', 'Прием родов'), ('550$', 'Стомотологическое лечение')], max_length=30, null=True, verbose_name='Стоимость'),
        ),
    ]
