# Generated by Django 4.2.5 on 2023-09-28 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_prices_cupping_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vet_clinic',
            name='servis_price',
        ),
        migrations.AlterField(
            model_name='doctors',
            name='profesh',
            field=models.CharField(max_length=20, verbose_name='Врач'),
        ),
        migrations.AlterField(
            model_name='prices',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Стоимость услуги'),
        ),
        migrations.AlterField(
            model_name='vet_clinic',
            name='doctor',
            field=models.ManyToManyField(to='catalog.doctors', verbose_name='Врач'),
        ),
        migrations.AlterField(
            model_name='vet_clinic',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='catalog.status', verbose_name='Профессия'),
        ),
    ]
