# Generated by Django 4.2.5 on 2023-09-28 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_remove_vet_clinic_servis_price_alter_doctors_profesh_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prices',
            name='price',
        ),
        migrations.AddField(
            model_name='prices',
            name='pric',
            field=models.IntegerField(null=True, verbose_name='Стоимость услуги'),
        ),
    ]
