# Generated by Django 4.2.5 on 2023-09-28 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_remove_prices_price_prices_pric'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vet_clinic',
            name='prices',
        ),
        migrations.DeleteModel(
            name='Prices',
        ),
    ]
